# ------------------- 全新标准配置 -------------------
port: 7890
socks-port: 7891
redir-port: 7893
allow-lan: true
bind-address: '*'
log-level: info
external-controller: '0.0.0.0:9090'
secret: '20050102.'

# 手动定义首选节点
proxies:
  - name: "美国D1-手动"
    type: trojan
    server: cmgd.ecydns.com
    port: 10037
    password: f4427bae-817a-34e4-aae0-9cc3a44427fb
    tls: true
    udp: true
    sni: usd.ecydns.com

# 订阅链接
proxy-providers:
  airport:
    type: http
    url: "https://owo.ecydy.com/link/IVmLC9QhcRx6IMOF?clash=1"
    interval: 3600
    path: ./providers/airport.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

# 代理组
proxy-groups:
  - name: "自动选择"
    type: url-test
    use:
      - airport
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: "PROXY"
    type: select
    proxies:
      - "美国D1-手动"
      - "自动选择"

# 规则
rules:
  - MATCH,PROXY
# ------------------- 配置结束 -------------------
# ------------------- DNS 完美分流配置 -------------------
dns:
  enable: true
  listen: 0.0.0.0:5353
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  
  # 国内域名使用的DNS (快速、可靠)
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  # 国外域名使用的DNS (防污染)
  nameserver:
    - https://dns.google/dns-query # Google DNS over HTTPS
    - tls://1.1.1.1 # Cloudflare DNS over TLS

  # nameserver 解析失败时的备用DNS
  fallback:
    - tls://8.8.4.4
    - https://doh.pub/dns-query

  # 规则: 匹配 geosite:cn 列表的域名，使用 default-nameserver 解析
  # 其他所有域名，默认使用 nameserver 解析
  nameserver-policy:
    'geosite:cn':
      - default-nameserver
# ------------------- 配置结束 -------------------
